### ISSUE TITLE
Regression when I upgrade from 5.0 to 5.1: Missing SelectionModel

### ISSUE THREAD

**Issue by tarasglek** [projectstorm/react-diagrams#198]
Typescript compiler now complains:
.../node_modules/storm-react-diagrams/dist/@types/src/actions/MoveItemsAction.d.ts
(2,32): Cannot find module '../models/SelectionModel'.

I'm using https://github.com/Microsoft/TypeScript-React-Starter if  you need to reproduce this.

**Comment by dylanvorster** [comment]
Fixed in 5.1.1
